# ---- ericsantos.eu (site raiz — HTML estático) ----

server {
    listen 443 ssl;
    server_name ericsantos.eu www.ericsantos.eu;

    root  /opt/ericsantos.eu;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }

    # managed by Certbot
    ssl_certificate     /etc/letsencrypt/live/ericsantos.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ericsantos.eu/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name ericsantos.eu www.ericsantos.eu;

    if ($host = www.ericsantos.eu) { return 301 https://$host$request_uri; }
    if ($host = ericsantos.eu)     { return 301 https://$host$request_uri; }

    return 404;
}
